# services:
#   app:
#     build: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: root123
#       MYSQL_DATABASE: user_management
#       MYSQL_USER: app_user
#       MYSQL_PASSWORD: app_password
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./mysql_data:/var/lib/mysql

version: "3.9" # Modern version specification

services:
  app:
    build:
      context: . # Build from the current directory
    ports:
      - "8080:8080" # Map container's port 8080 to host's port 8080
    depends_on:
      - db # Ensure db starts before app

  db:
    image: mysql:8.0 # Use the official MySQL 8.0 image
    container_name: user_management_db # Optional but helps for easy identification
    environment:
      MYSQL_ROOT_PASSWORD: root123 # Root password
      MYSQL_DATABASE: user_management # Initial database name
      MYSQL_USER: app_user # MySQL username
      MYSQL_PASSWORD: app_password # MySQL password
    ports:
      - "3306:3306" # Expose MySQL port 3306
    volumes:
      - ./mysql_data:/var/lib/mysql # Persist data on host
